Ecommerce.WebApp/Areas/Admin/Controllers/Media/MediaApiController.cs
using Ecommerce.Core.Models;
using Ecommerce.Core.Services;
using Ecommerce.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Ecommerce.WebApp.Areas.Admin.Controllers.Media
{
    [Area("admin")]
    [Route("admin/api/media")]
    public class MediaApiController : Controller
    {
        private readonly MediaService _service;
        private readonly IApi _api;

        public MediaApiController(MediaService service, IApi api)
        {
            _service = service;
            _api = api;
        }

        /// <summary>
        /// Gets single media
        /// </summary>
        /// <returns>The list model</returns>
        [Route("{id}")]
        [HttpGet]
        public async Task<IActionResult> Get(Guid id)
        {
            var media = await _service.GetById(id);
            if (media == null)
            {
                return NotFound();
            }

            return Ok(media);
        }

        /// <summary>
        /// Gets the image url for the specified dimensions.
        /// </summary>
        /// <param name="id">The unqie id</param>
        /// <param name="width">The optional width</param>
        /// <param name="height">The optional height</param>
        /// <returns>The public url</returns>
        [Route("url/{id}/{width?}/{height?}")]
        [HttpGet]
        public async Task<IActionResult> GetUrl(Guid id, int? width = null, int? height = null)
        {
            if (!width.HasValue)
            {
                var media = await _api.Media.GetByIdAsync(id);

                if (media != null)
                {
                    return Redirect(media.PublicUrl);
                }
                return NotFound();
            }
            else
            {
                return Redirect(await _api.Media.EnsureVersionAsync(id, width.Value, height));
            }
        }

        /// <summary>
        /// Gets the list model.
        /// </summary>
        /// <returns>The list model</returns>
        [Route("list/{folderId:Guid?}")]
        [HttpGet]
        public async Task<MediaListModel> List(Guid? folderId = null, [FromQuery]MediaType? filter = null, [FromQuery] int? width = null, [FromQuery] int? height = null)
        {
            return await _service.GetList(folderId, filter, width, height);
        }

        /// <summary>
        /// Saves the meta information for the given media asset.
        /// </summary>
        /// <param name="model">The media model</param>
        [Route("meta/save")]
        [HttpPost]
        public async Task<IActionResult> SaveMeta(MediaListModel.MediaItem model)
        {
            if (await _service.SaveMeta(model))
            {
                return Ok(new StatusMessage
                {
                    Type = StatusMessage.Success,
                    Body = "The meta information was succesfully updated"
                });
            }
            else
            {
                return Ok(new StatusMessage
                {
                    Type = StatusMessage.Error,
                    Body = "An error occured when updating the meta information"
                });
            }
        }

        [Route("folder/save")]
        [HttpPost]
        
        public async Task<IActionResult> SaveFolder(MediaFolderModel model, MediaType? filter = null)
        {
            try
            {
                await _service.SaveFolder(model);

                var result = await _service.GetList(model.ParentId, filter);

                //result.Status = new StatusMessage
                //{
                //    Type = StatusMessage.Success,
                //    Body = "The folder <code>{0}</code> was saved"
                //};

                return Ok(result);
            }
            catch (ValidationException e)
            {
               
                var result = new StatusMessage
                {
                    Type = StatusMessage.Error,
                    Body = e.Message
                };
                return BadRequest(result);
            }
        }

        [Route("folder/delete/{id:Guid}")]
        [HttpGet]
        
        public async Task<IActionResult> DeleteFolder(Guid id)
        {
            try
            {
                var folderId = await _service.DeleteFolder(id);

                var result = await _service.GetList(folderId);

                //result.Status = new StatusMessage
                //{
                //    Type = StatusMessage.Success,
                //    Body = "The folder was successfully deleted"
                //};

                return Ok(result);
            }
            catch (ValidationException e)
            {
               
                var result = new StatusMessage
                {
                    Type = StatusMessage.Error,
                    Body = e.Message
                };
                return BadRequest(result);
            }
        }

        /// <summary>
        /// Adds a new media upload.
        /// </summary>
        /// <param name="model">The upload model</param>
        [Route("upload")]
        [HttpPost]
        [Consumes("multipart/form-data")]
        
        public async Task<IActionResult> Upload([FromForm] MediaUploadModel model)
        {
            // Allow for dropzone uploads
            if (!model.Uploads.Any())
            {
                model.Uploads = HttpContext.Request.Form.Files;
            }

            try
            {
                var uploaded = await _service.SaveMedia(model);

                if (uploaded == model.Uploads.Count())
                {
                    return Ok(new StatusMessage
                    {
                        Type = StatusMessage.Success,
                        Body = "Uploaded all media assets"
                    });
                }
                else if (uploaded == 0)
                {
                    return Ok(new StatusMessage
                    {
                        Type = StatusMessage.Error,
                        Body = "Could not upload the media assets"
                    });
                }
                else
                {
                    return Ok(new StatusMessage
                    {
                        Type = StatusMessage.Information,
                        Body = "Uploaded {0} of {1} media assets"
                    });
                }
            }
            catch (Exception e)
            {
                return BadRequest(new StatusMessage
                {
                    Type = StatusMessage.Error,
                    Body = e.Message
                });
            }
        }

        [Route("move/{mediaId}/{folderId?}")]
        [HttpGet]
        
        public async Task<IActionResult> Move(Guid mediaId, Guid? folderId)
        {
            try
            {
                if (mediaId != folderId)
                {
                    var media = await _api.Media.GetByIdAsync(mediaId);
                    if (media != null)
                    {
                        await _api.Media.MoveAsync(media, folderId);

                        return Ok(new StatusMessage
                        {
                            Type = StatusMessage.Success,
                            Body = $"{media.Filename} was successfully moved."
                        });
                    }

                    var folder = await _api.Media.GetFolderByIdAsync(mediaId);
                    if (folder != null)
                    {
                        folder.ParentId = folderId;
                        await _api.Media.SaveFolderAsync(folder);

                        return Ok(new StatusMessage
                        {
                            Type = StatusMessage.Success,
                            Body = $"{folder.Name} was successfully moved."
                        });
                    }
                    return BadRequest(new StatusMessage
                    {
                        Type = StatusMessage.Error,
                        Body = "The media file was not found."
                    });
                }
                return BadRequest();
            }
            catch (Exception e)
            {
                return BadRequest(new StatusMessage
                {
                    Type = StatusMessage.Error,
                    Body = e.Message
                });
            }
        }

        [Route("delete/{id:Guid}")]
        [HttpGet]
        
        public async Task<IActionResult> Delete(Guid id)
        {
            try
            {
                var folderId = await _service.DeleteMedia(id);
                var result = await _service.GetList(folderId);

                var result1 = new StatusMessage
                {
                    Type = StatusMessage.Success,
                    Body ="The media file was successfully deleted"
                };

                return Ok(result1);
            }
            catch (ValidationException e)
            {
               
                var result = new StatusMessage
                {
                    Type = StatusMessage.Error,
                    Body = e.Message
                };
                return BadRequest(result);
            }
        }
    }
}

Ecommerce.WebApp/Areas/Admin/Controllers/Media/MediaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Ecommerce.WebApp.Areas.Admin.Controllers.Media
{
    [Area("admin")]
    public class MediaController : Controller
    {
        [Route("admin/media")]
        public IActionResult list()
        {
            return View();
        }
    }
}

Ecommerce.WebApp/Areas/Admin/Views/Media/list.cshtml
@{
    ViewData["Title"] = "list";
    Layout = "~/Areas/View/Shared/_Layout.cshtml";
}


@section scripts
{
    <script src="@Url.Content("~/Admin/assets/Media/ecommerce.media.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Admin/assets/Media/ecommerce.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Admin/assets/Media/ecommerce.media.min.js")" type="text/javascript"></script>
    <script>
      
            media.load("0", true);
      
    </script>
}
<div id="media">
    <div class="top">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb mb-0">
                <li class="breadcrumb-item">Content</li>
                <li class="breadcrumb-item active" aria-current="page">Media</li>
            </ol>
        </nav>

        <div v-if="!loading" class="container-fluid">
            <div class="top-nav">
                @*@foreach (var action in Ecommerce.Actions.Toolbars.MediaList)
                    {
                        <partial name="@action.ActionView" />
                    }*@
            </div>
        </div>
    </div>

    <div class="app" :class="{ ready: !loading }">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-3 col-4">
                    <div class="mb-3">
                        <button class="btn btn-sm btn-primary" v-on:click="isAdding = true">
                            <i class="fas fa-plus"></i>
                        </button>
                        <button v-if="currentFolderId != null" v-on:click="editFolder()" class="btn btn-sm btn-primary">
                            <i class="fas fa-pen"></i>
                        </button>
                        <button v-if="currentFolderId != null && canDelete" class="btn btn-sm btn-danger" v-on:click.prevent="removeFolder(currentFolderId)">
                            <i class="fas fa-trash"></i>
                        </button>
                    </div>
                    <div class="dd folder-container">
                        <ol class="folders dd-list">
                            <li class="droppable" :class="{ active: currentFolderId === null }" v-on:dragover="dragover" v-on:dragleave="dragleave" v-on:drop="drop($event, null)">
                                <a v-on:click.prevent="load()" href="#">
                                    <i class="fas fa-hdd"></i>Media
                                    <span class="badge badge-light float-right">{{ rootCount }}</span>
                                </a>
                                <ol v-if="currentFolderId === null && isAdding" class="dd-list">
                                    <form v-on:submit.prevent="addFolder()" class="d-inline-block">
                                        <i class="fas fa-folder"></i><input id="add-folder" type="text" v-on:keyup.esc="isAdding = false" v-model="folder.name" class="form-control form-control-sm d-inline-block w-auto">
                                    </form>
                                </ol>
                            </li>
                            <ol class="dd-list">
                                <folder-item v-for="item in structure" v-bind:key="item.id" v-bind:selected="currentFolderId" v-bind:item="item"></folder-item>
                            </ol>
                        </ol>
                    </div>
                </div>
                <div class="col-lg-9 col-8">
                    <div class="mb-3">
                        <button v-on:click="showGallery()" class="btn btn-sm" :class="{ 'btn-light': !listView, 'btn-white': listView }">
                            <i class="fas fa-table"></i>
                        </button>
                        <button v-on:click="showList()" class="btn btn-sm" :class="{ 'btn-light': listView, 'btn-white': !listView }">
                            <i class="fas fa-list"></i>
                        </button>
                    </div>

                    <div id="media-upload-container" class="dropzone-container mb-3">
                        <form action="@Url.Action("Upload", "MediaApi")" class="dropzone needsclick dz-clickable" enctype="multipart/form-data">
                            <input type="hidden" name="Model.ParentId" v-model="currentFolderId" />
                            <div class="dz-message needsclick text-center">
                                <span class="fas fa-cloud-upload-alt"></span>
                                Drop files here or click to upload.
                            </div>
                            <div class="file-list"></div>
                        </form>
                        <ul class="media-list list-unstyled"></ul>
                    </div>


                    <partial name="Partial/_MediaGallery" />
                    <partial name="Partial/_MediaList" />
                </div>
            </div>
        </div>
    </div>
    <partial name="Partial/_MediaFolderModal" />
</div>